extends Node

var used_names = []

func generate_name() -> String:
	var name = PossibleNames[randi()%PossibleNames.size()]
	used_names.push_back(name)
	return name

func clear_used_names() -> void:
	used_names.clear()


	
const PossibleNames = [
	"Roosdijk",
	"Dammerveen",
	"Waverdam",
	"Hel",
	"Veendijk",
	"Schaapdijk",
	"Blankewegen",
	"Dijkbreuk",
	"Den Dijk",
	"Broek op keringland",
	"Paramimeer",
	"Nieuw-Groogiveen",
	"Langsen",
	"Knokselt",
	"Antisart",
	"Elterheim",
	"Goedenbeek",
	"Cootereen",
	"Waaldert",
	"Laucour",
	"Drie Laag Dijk",
	"Nieuw-Colologne",
	"Nieuweind",
	"Heldoorn",
	"Hoofdrichem",
	"Zoteind",
	"Limur",
	"Heermelo",
	"Herfeld",
	"Rauenbog",
	"Nijdam",
	"Frisiedeln",
	"Vlissinglem",
	"Lenrau",
	"Oudenloon",
	"Kerkenhal",
	"Griesnau",
	"Naamlen",
	"Vohengeismar",
	"Zuiderren",
	"Nieuw Uppo Dijk",
	"Burgpen",
	"Warelaas",
	"Tullabriggan",
	"Terhof",
	"Ulmhof",
	"Kufsee",
	"Kloosterhoven",
	"Tourschaat",
	"Haguegneux",
	"Eppelscheid",
	"Southbar",
	"Wijnloopen",
	"Maanveen",
	"Hollastadt",
	"Isselgeismar",
	"Graanstones",
	"Wolvendam",
	"Drachmegen",
	"Maasselt",
	"Vrijhoven",
	"Hoogstraten",
	"Dilon",
	"Steenvorden",
	"Wijnfort",
	"Ljouwert",
	"Snits",
	"Dorp zonder naam",
	"Pieterplas dorp",
	"Wolkbreuk aan Zee",
	"Petterflatsedijk",
	"Rode-gordijn stad",
	"Zeemeermin",
	"Nietzeeland",
	"Meerwater",
	"Fiets op Stelten",
	"Onderwaterwijk",
	"Giedodyk",
	"Den Frikandel",
	"Zonderzon",
	"Tegenvoort",
	"Pepernotenstad",
	"Hoog-Henkerveen",
	"Vogeliuserwaard",
	"Borrelnotermeer",
	"Kaaskopperwijk",
	"Wijk-aan-Oceaan",
	"Berg-op-Dijk",
	"Hoogmoedoverveen",
	"Laagstadt",
	"Den Egelsbosch",
	"Patatjemetstad",
	"Overwijkerzeedam",
	"Hoog-Oranjebovenwatersveen",
	"Sint-Johan's-meer",
	"Schimmelhaven",
	"Haven zonder Water",
	"Drakendijk",
	"Kikkerdorp",
	"Steendijk",
	"Klein Rif Barrière",
	"Bijbelbelt-Op-Water",
	"Duisterveen",
]
	
	
